### ISSUE TITLE
this team is fake

### ISSUE THREAD

**Issue by nerdtron123** [coffeebreakerz/iOS_Useful_Resources#1]
https://github.com/coffeebreakerz/iOS_Useful_Resources/blob/master/jailbreak_untethered.txt you can't modify kernelcache or soft-brick

**Comment by coffeebreakerz** [comment]
Lol, you might not be able too, but the kernel can ;)
Also it is a hypothesis never said it would be true.

**Comment by nerdtron123** [comment]
okay mister fake
